codecov:
  branch: master

coverage:
  precision: 2
  round: up

  ignore:
      - "test/com/transgressoft/musicott/tests/JavaFxTestBase.java"
      - "test/com/transgressoft/musicott/tests/MusicottTestSuite.java"
